version: "3.5"

services:
  mongo-db:
    image: mongo
    container_name: msksBox-mongodb
    ports:
      - "27017-27019:27017-27019"
    networks:
      - msksBox-network

networks:
  msksBox-network:
    name: msksBox-network
    driver: bridge